### ISSUE TITLE
change controller to another node, if all nodes are ok

### ISSUE THREAD

**Issue by pantherra** [LINBIT/drbd-reactor#4]
Hello! How can i transfer linstor-controller role thats currently running on node, to another node in cluster? I have 3 node cluster setup with proxmox. 
 For example - i want make sure, that drbd-reactor change linstor-controller node correctly.

**Comment by rck** [comment]
```
$ drbd-reactorctl disable --now $howeveryoucalledit
# check to see if another node took over:
$ drbd-reactorctl status $howeveryoucalledit # / drbdsetup status 
$ drbd-reactorctl enable $howeveryoucalledit # to make reactor feel responsible for the resource again
```

As all nodes should be equally fine, there is no way you could directly move it to a *particular* node. With the steps shown you can move it away from the node that currently runs the services to some other *unspecified* node.

**Comment by pantherra** [comment]
> drbd-reactorctl enable

Until i manually change role on resource linstor_db to secondary on active node, drbd-reactor doesnt start on other node. Currently linstor-controller nodes changes automatically

**Comment by rck** [comment]
I'm not sure I fully understood, but maybe it helps if I explain what enable does (and what it does not):
- you disabled the plugin (or all of them by not giving a name). That alone would have kept the state as it was. with `--now`, the generated `drbd-services@$howeveryoucalledit.target` got stopped as well, which stopped all controlled services and demoted the DRBD device to Secondary. Another node saw that it might promote, did so, and started the services
- `drbd-reactorctl enable`: the the plugin (or all of them by not giving a name) got enabled and threads got started. Obviously the newly spawned promoter plugin did exectly nothing, because it saw that that the resource is already active on another node. So it is idling around till the currently active node fails, or the promoter craches, or you shutdown, or you disable the plugin.

side note: never ever start/stop parts of the generated units manually. use `drbd-reactorctl`, or if you know what you are doing the `drbd-services@howeveryoucalledit.target`
